### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [devildani/email_permutations#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.6.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary email-permutations -w /tmp/ext email-permutations==0.6.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting email-permutations==0.6.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/d55/b3e02c46f9890/email_permutations-0.6.0.tar.gz (1.7 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-pfl_doti/email-permutations/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-pfl_doti/email-permutations/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-pfl_doti/email-permutations/pip-egg-info
         cwd: /tmp/pip-wheel-pfl_doti/email-permutations/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-pfl_doti/email-permutations/setup.py", line 3, in <module>
        with open("README.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by thatch** [comment]
This appears to work with current versions of setuptools/pip from the repo, but fails against the released sdist.
